-- Generated posts table for social media post creator
-- Stores text + image posts generated by AI

create table public.generated_posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  text text,
  image_url text,
  storage_path text,
  config jsonb,
  is_favorite boolean default false,
  created_at timestamptz default now()
);

alter table public.generated_posts enable row level security;

-- Performance indexes
create index generated_posts_user_id_idx on public.generated_posts(user_id);
create index generated_posts_created_at_idx on public.generated_posts(created_at desc);

-- RLS Policies
create policy "Users can insert own posts"
on public.generated_posts for insert
to authenticated
with check ( (select auth.uid()) = user_id );

create policy "Users can view own posts"
on public.generated_posts for select
to authenticated
using ( (select auth.uid()) = user_id );

create policy "Users can update own posts"
on public.generated_posts for update
to authenticated
using ( (select auth.uid()) = user_id )
with check ( (select auth.uid()) = user_id );

create policy "Users can delete own posts"
on public.generated_posts for delete
to authenticated
using ( (select auth.uid()) = user_id );
